# Check internal links in markdown files
name: Internal Linkcheck

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  internal-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Check Internal Links
      run: |
        find README.md about documentation installation support tutorials \
          -type f -name '*.md' -print0 | \
          xargs -0 -n 1 npx markdown-link-check@3.10.3 \
            --config .markdown_linkcheck_internal.json
