# Check formatting of markdown files
name: Markdown Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run MarkdownLint
        run: >
          npx markdownlint-cli2
          --disable MD013
          "documentation/**/*.md"
          "imported/**/*.md"
          "installation/**/*.md"
          "README.md"
          "about/**/*.md"
          "tutorials/**/*.md"
          "support/**/*.md"
